from django.core.management.base import BaseCommand
from tests.models import Question

# ✅ Full list of 181 verified questions
QUESTIONS = [
    (1, "I rarely worry."), (2, "I often eat too much."), (3, "I usually like to spend my free time with people."),
    (4, "I take charge."), (5, "I am always busy."), (6, "I radiate joy."), (7, "I do not like poetry."),
    (8, "I distrust people."), (9, "I tell other people what they want to hear so that they will do what I want them to do."),
    (10, "I anticipate the needs of others."), (11, "I believe that I am better than others."),
    (12, "I sympathize with the homeless."), (13, "I keep things tidy."), (14, "I am a highly disciplined person."),
    (15, "I jump into things without thinking."), (16, "I admire a really clever scam."),
    (17, "I like to own things that impress people."), (18, "I try to be with someone else when I'm feeling badly."),
    (19, "I feel others’ emotions."), (20, "I talk a lot."), (21, "I try to avoid speaking in public."),
    (22, "I am usually active and full of energy."), (23, "I am patient with people who annoy me."),
    (24, "I am easily annoyed."), (25, "I push myself very hard to succeed."), (26, "I do not like art."),
    (27, "I love to hear about other countries and cultures."), (28, "I am considered to be kind of eccentric."),
    (29, "I worry about what people think of me."), (30, "I am very shy in social situations."),
    (31, "I don't have much energy."), (32, "I don't think that laws apply to me."),
    (33, "I have frequent mood swings."), (34, "I hold a grudge."), (35, "I like to act on a whim."),
    (36, "I have felt the presence of another person when he or she was not really there."),
    (37, "I seem to derive less enjoyment from interacting with people than others do."),
    (38, "I love to be the center of attention."), (39, "I don't let others cut in front of me in line."),
    (40, "I insist that others do things my way."), (41, "I am a firm believer in thinking things through."),
    (42, "I dislike changes."), (43, "I read a large variety of books."), (44, "I love excitement."),
    (45, "I would rather spend money than save it."), (46, "I enjoy being reckless."),
    (47, "I have never cared much what others thought of me."),
    (48, "I usually get right to work on something that needs to be done as soon as I think of it."),
    (49, "I often have the feeling that others laugh or talk about me."), (50, "I try to forgive and forget."),
    (51, "I feel little concern for others."), (52, "I do things out of revenge."),
    (53, "I have felt contact with a divine power."), (54, "I am devoted to religion."),
    (55, "I was a better than average student when I was in school."), (56, "I felt close to my parents when I was a child."),
    (57, "I feel a sense of worthlessness or hopelessness."), (58, "I am interested in science."),
    (59, "I believe that most questions have one right answer."), (60, "I tend to feel happy and irritable at the same time."),
    (61, "I believe it is always better to be safe than sorry."), (62, "I rarely get irritated."),
    (63, "I wanted to run away from home when I was a child."), (64, "I often enjoy telling jokes or behaving in a humorous manner."),
    (65, "I make enemies."), (66, "I am fascinated by how machines work."),
    (67, "I disliked math in school."), (68, "I have a rich vocabulary."),
    (69, "I like to read."), (70, "I don't care about dressing nicely."),
    (71, "I worry about things."), (72, "I am easily intimidated."),
    (73, "I love large parties."), (74, "I seldom daydream."),
    (75, "I crave the experience of great art."), (76, "I tend to vote for liberal political candidates."),
    (77, "I feel sympathy for those who are worse off than myself."), (78, "I use my charm to get attention."),
    (79, "I avoid activities that are physically dangerous."), (80, "I immediately feel sad when hearing of an unhappy event."),
    (81, "I can make myself work on a difficult task even when I don't feel like trying."),
    (82, "I pay too little attention to details."), (83, "I do not like to visit museums."),
    (84, "I have no special urge to do something original."), (85, "I have difficulty showing affection."),
    (86, "I find it easy to manipulate others."), (87, "I cannot imagine lying or cheating."),
    (88, "I talk to a lot of different people at parties."), (89, "I dislike having authority over others."),
    (90, "I often forget to put things back in their proper place."), (91, "I act without consulting others."),
    (92, "I like to visit new places."), (93, "I have time for play and relaxation."),
    (94, "I am open to new experiences."), (95, "I don't care what others think."),
    (96, "I am not sure where my life is going."), (97, "I would like to have more power than other people."),
    (98, "I believe in universal harmony."), (99, "I am skilled in handling social situations."),
    (100, "I try to avoid complex people."), (101, "I see myself as a good leader."),
    (102, "I avoid crowds."), (103, "I am not good at telling jokes."),
    (104, "I don't use harsh language."), (105, "I am able to fix electrical-wiring problems."),
    (106, "I enjoy games of strategy."), (107, "I was a slow learner in school."),
    (108, "I often stop to analyze how I'm feeling."), (109, "I get deeply immersed in music."),
    (110, "I like to solve complex problems."), (111, "I am concerned about others."),
    (112, "I like to tidy up."), (113, "I don't feel the need to be close to others."),
    (114, "I love my enemies."), (115, "I have an imagination that stretches beyond that of my friends."),
    (116, "I find it difficult to organize tasks and activities."),
    (117, "I feel that life has no meaning."), (118, "I like being the authority who has everyone's attention."),
    (119, "I have attacked someone physically."), (120, "I like to stand out in a crowd."),
    (121, "I get upset if others change the way that I have arranged things."),
    (122, "I want things to proceed according to plan."),
    (123, "I am often in a bad mood."),
    (124, "I want to be the very best."),
    (125, "I feel used by other people."),
    (126, "I am able to control my cravings."),
    (127, "I know what to say to make people feel good."),
    (128, "I get so involved with things that I forget the time."),
    (129, "I am often bored."),
    (130, "I demand attention."),
    (131, "I want everything to be 'just right'."),
    (132, "I would love to explore strange places."),
    (133, "I amuse my friends."),
    (134, "I worry about being embarrassed."),
    (135, "I want to be left alone."),
    (136, "I don't know why I do some of the things I do."),
    (137, "I am exacting in my work."),
    (138, "I have difficulty imagining things."),
    (139, "I am not interested in theoretical discussions."),
    (140, "I don't enjoy being the object of jokes."),
    (141, "I plan my life logically."),
    (142, "I indulge in my fantasies."),
    (143, "I rarely cry during sad movies."),
    (144, "I get to work at once."),
    (145, "I wait for others to lead the way."),
    (146, "I have never hated anyone."),
    (147, "I need reassurance."),
    (148, "I feel emotions with extreme intensity."),
    (149, "I spend a lot of time reading."),
    (150, "I don't try to figure myself out."),
    (151, "I break my promises."),
    (152, "I need a push to get started."),
    (153, "I have a colorful and dramatic way of talking about things."),
    (154, "I come up with new ways to do things."),
    (155, "I don't like to spend money."),
    (156, "I believe in a universal power or God."),
    (157, "I am the life of the party."),
    (158, "I don't attempt to conform to society's expectations."),
    (159, "I wonder how I got to be the way that I am."),
    (160, "I feel short-changed in life."),
    (161, "I will not probe deeply into a subject."),
    (162, "I panic easily."),
    (163, "I have a strong personality."),
    (164, "I prefer to participate fully rather than view life from the sidelines."),
    (165, "I spend more money than I should."),
    (166, "I make people feel at ease."),
    (167, "I am always prepared."),
    (168, "I keep my feelings to myself, regardless of how unhappy I am."),
    (169, "I spend more money than I have."),
    (170, "I love to chat."),
    (171, "I am hard to get to know."),
    (172, "I get back at people who insult me."),
    (173, "I am relaxed most of the time."),
    (174, "I check on things more often than necessary."),
    (175, "I get too tired to do anything."),
    (176, "I don't call attention to myself."),
    (177, "I am a good listener."),
    (178, "I shout or scream when I'm angry."),
    (179, "I disclose my intimate thoughts."),
    (180, "I am under constant pressure."),
    (181, "I believe that most people would lie to get ahead.")
]

class Command(BaseCommand):
    help = "Load all 181 AMBI test questions into the database."

    def handle(self, *args, **kwargs):
        try:
            Question.objects.all().delete()
            for order, text in QUESTIONS:
                Question.objects.create(order=order, text=text)
            self.stdout.write(self.style.SUCCESS("✅ Successfully loaded all 181 AMBI questions."))
        except Exception as e:
            self.stderr.write(self.style.ERROR(f"❌ Error loading questions: {str(e)}"))
